### ISSUE TITLE
Add issue link for making android plugins work nicely

### ISSUE THREAD

**Issue by ldaley** [gradle-guides/migrating-build-logic-from-groovy-to-kotlin#8]
I think it's likely that Android people are going to be our early adopters. We should give them some (non false) hope that they will be able to eventually use the android extension without the explicit typing.

**Comment by eskatos** [comment]
The guide uses the Android Gradle Plugin example when explaining how to keep scripts declarative already: https://guides.gradle.org/migrating-build-logic-from-groovy-to-kotlin/#declarative-scripts and points to the corresponding Google issue.

Did you have something else in mind?

**Comment by autonomousapps** [comment]
I just came here to file a related issue. I'll comment here instead. I had a conversation with @bamboo on Slack [here](https://gradle.slack.com/archives/C14BJHC2K/p1537816785000100). My tl;dr is that the advice in that specific section is bad/wrong and we should change it. Why is it bad/wrong?
1. It doesn't work.

I think that covers it. You get an error like this:
> CONFIGURE FAILED in 33s
Unable to load class 'com.android.build.gradle.BaseExtension'.
Possible causes for this unexpected error include:<ul><li>Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
Re-download dependencies and sync project (requires network)</li><li>The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.
Stop Gradle build processes (requires restart)</li><li>Your project may be using a third-party plugin which is not compatible with the other plugins in the project or the version of Gradle requested by the project.</li></ul>In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.

Instead, we should recommend the approach adopted by the [hello-android](https://github.com/gradle/kotlin-dsl/tree/master/samples/hello-android) sample project. Essentially, the root `build.gradle` has this (note: this is Groovy, I didn't try the conversion to Kotlin for the root script yet):
```gradle
buildscript {
    ext.kotlin_version = '1.2.71'
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.4' // the critical point
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}
```
And then `app/build.gradle.kts` should have this:
```gradle
plugins {
    id("com.android.application")
    id("kotlin-android")
    id("kotlin-android-extensions") // unnecessary but common
}

// and now this is possible, because we used `plugins { }`
android {
    compileSdkVersion(28)
    defaultConfig {
        applicationId = "com.gradle.example"
        minSdkVersion(21)
        targetSdkVersion(28)
        versionCode = 1
        versionName = "1.0"
        testInstrumentationRunner = "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            isMinifyEnabled = false
            proguardFiles(getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro")
        }
    }
}
```
PS: in `buildSrc`, I defined an extension function `release` because, bizarrely, it wasn't already available:
```kotlin
import org.gradle.api.Action
import org.gradle.api.NamedDomainObjectContainer

fun <T> NamedDomainObjectContainer<T>.release(action: Action<in T>) = getByName("release", action)
```

PPS: How do we use `ext` in Kotlin build scripts?

**Comment by eskatos** [comment]
Both Luke's and Tony's feedback here should be addressed by https://github.com/gradle/gradle/pull/7459

**Comment by eskatos** [comment]
Closing as delivered in https://github.com/gradle/gradle/pull/7459
